## Roteiro

## Configurando Ambiente

In [ ]:
%pip install -r ../requirements.txt

Requirement already satisfied: pandas>=2.2.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from -r ../requirements.txt (line 1)) (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from -r ../requirements.txt (line 2)) (2.4.4)
Requirement already satisfied: matplotlib>=3.8.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from -r ../requirements.txt (line 3)) (3.10.9)
Requirement already satisfied: seaborn>=0.13.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from -r ../requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from pandas>=2.2.0->-r ../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (26.0)
Requirement already satisfied: pillow>=8 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from matplotlib>=3.8.0->-r ../requirements.txt (line 3)) (3.3.2)
Requirement already satisfied: six>=1.5 in /home/sqt/anaconda3/envs/ppcd/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->-r ../requirements.txt (line 1)) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

### Bibliotecas

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Coleta dos Dados

Lendo e verificando o banco de dados

In [ ]:
arquivo = 'gapminder_full.csv'

In [ ]:
df = pd.read_csv(arquivo, sep=',')

### Visualização

In [ ]:
df.head()

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3  Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4  Afghanistan  1972  13079460.0      Asia   36.088  739.981106

### Funções

### Tratamento de dados

## Tratamento e Armazenamento

In [ ]:
filtro = df["country"] == "Kuwait"
df[filtro]

df[filtro].head(20)

    country  year        pop continent  lifeExp     gdpPercap
884  Kuwait  1952   160000.0      Asia   55.565  108382.35290
885  Kuwait  1957   212846.0      Asia   58.033  113523.13290
886  Kuwait  1962   358266.0      Asia   60.470   95458.11176
887  Kuwait  1967   575003.0      Asia   64.624   80894.88326
888  Kuwait  1972   841934.0      Asia   67.712  109347.86700
889  Kuwait  1977  1140357.0      Asia   69.343   59265.47714
890  Kuwait  1982  1497494.0      Asia   71.309   31354.03573
891  Kuwait  1987  1891487.0      Asia   74.174   28118.42998
892  Kuwait  1992  1418095.0      Asia   75.190   34932.91959
893  Kuwait  1997  1765345.0      Asia   76.156   40300.61996
894  Kuwait  2002  2111561.0      Asia   76.904   35110.10566
895  Kuwait  2007  2505559.0      Asia   77.588   47306.98978

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1736 entries, 0 to 1735
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1736 non-null   object
 1   year       1736 non-null   int64
 2   pop        1736 non-null   float64
 3   continent  1736 non-null   object
 4   lifeExp    1736 non-null   float64
 5   gdpPercap  1736 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 81.5+ KB

In [ ]:
df["country"]=df["country"].astype("string")
df["continent"]=df["continent"].astype("string")
df["pop"]=df["pop"].astype("int")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1736 entries, 0 to 1735
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1736 non-null   string
 1   year       1736 non-null   int64
 2   pop        1736 non-null   int64
 3   continent  1736 non-null   string
 4   lifeExp    1736 non-null   float64
 5   gdpPercap  1736 non-null   float64
dtypes: float64(2), int64(2), string(2)
memory usage: 81.5 KB

### Descrição dos dados

In [ ]:
dataset.columns

Index(['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap'], dtype='str')

##### Colunas com valores numéricos:

In [ ]:
numeric_cols = dataset.select_dtypes(include=["number"]).columns
print(numeric_cols)

Index(['year', 'pop', 'lifeExp', 'gdpPercap'], dtype='str')

##### Colunas com valores categóricos:

In [ ]:
cat_cols = dataset.select_dtypes(include=["object"]).columns
print(cat_cols)

Index(['country', 'continent'], dtype='str')

/tmp/ipykernel_222498/3641821407.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = dataset.select_dtypes(include=["object"]).columns

In [ ]:
df.describe()

              year           pop      lifeExp      gdpPercap
count  1736.000000  1.736000e+03  1736.000000    1736.000000
mean   1979.669931  3.156800e+07    59.511979    7240.155986
std      17.296364  1.172888e+08    12.956028    9839.873695
min    1952.000000  6.001100e+04    23.599000     241.165876
25%    1967.000000  2.818694e+06    48.245000    1202.060309
50%    1982.000000  7.150606e+06    60.808000    3534.772106
75%    1997.000000  1.977102e+07    70.945000    9380.254270
max    2007.000000  1.318683e+09    82.603000  113523.132900

---

Encontrando e eliminando dados duplicados

In [ ]:
df.duplicated().sum()

np.int64(32)

### Dados duplicados

In [ ]:
df = df.drop_duplicates()

### Dados Nulos

In [ ]:
df.isna().sum()

country      0
year         0
pop          0
continent    0
lifeExp      0
gdpPercap    0
dtype: int64

# Análise descritiva e exploratória

### Identificação e Ajuste de Outliers

Realizamos as análises da base de dados, e encontrados dados discrepantes com relação ao PIB do Kwait.

Os valores estão muito altos, conforme GRAFICO 1.
<apresenta o gráfico com o erro>
 
Buscamos na base de dados do 'https://www.gapminder.org/data/' no menu de 'GPD per capita, PPP (constant 2021 internacional $)' identificamos valores distintos.
<faz a leitura da base correta>
<apresenta o gráfico correto>

#### Expectativa de vida por ano por país

#### PIB por ano e por País

#### PIB por continente

#### Análise Populacional para o PIB

#### Influência da Expectativa de Vida no PIB

#### Análise de Correlação